#ifndef PWM_CONFIG_H
#define PWM_CONFIG_H

#define PWM_CHANNEL_SERVO_1         0
#define PWM_CHANNEL_SERVO_2         1
#define PWM_CHANNEL_SERVO_3         2
#define PWM_CHANNEL_MOTOR_LEFT      3
#define PWM_CHANNEL_MOTOR_RIGHT     4
#define PWM_CHANNEL_CASCADE         5
#define PWM_CHANNEL_BASE_GEAR       6

#define PWM_FRQ_HZ_MOTOR_LEFT       1000
#define PWM_FRQ_HZ_MOTOR_RIGHT      1000
#define PWM_FRQ_HZ_CASCADE          1000
#define PWM_FRQ_HZ_BASE_GEAR        1000

#define PWM_RESOLUTION_MOTOR_LEFT   8
#define PWM_RESOLUTION_MOTOR_RIGHT  8
#define PWM_RESOLUTION_CASCADE      12
#define PWM_RESOLUTION_BASE_GEAR    8

#define PWM_MAX_DUTY_MOTOR_LEFT     1 << PWM_RESOLUTION_MOTOR_LEFT
#define PWM_MAX_DUTY_MOTOR_RIGHT    1 << PWM_RESOLUTION_MOTOR_RIGHT
#define PWM_MAX_DUTY_CASCADE        1 << PWM_RESOLUTION_CASCADE
#define PWM_MAX_DUTY_BASE_GEAR      1 << PWM_RESOLUTION_BASE_GEAR

#endif