#    To run the main robot:
#        pio run -e pico32 -t upload
#    To run with the monitor:
#        pio run -e pico32 -t upload -t monitor
#    To run one of the "tests":
#        pio run -e test_arm -t upload -t monior
#    If it's giving you a checksum error:
#        pio run -t erase


[env:pico32]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<*>
    -<test>
lib_deps = 
    sparkfun/SparkFun VL53L5CX Arduino Library@^1.0.3

[env:test_arm]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<actuators/Arm.cpp>
    +<actuators/Servo.cpp>
    +<actuators/BaseGear.cpp>
    +<actuators/Motor.cpp>
    +<sensors/MagneticEncoder.cpp>
    +<test/arm/test_arm.cpp>
lib_deps = 
    Adafruit SSD1306

[env:calibrate_arm]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<actuators/Arm.cpp>
    +<actuators/Servo.cpp>
    +<actuators/BaseGear.cpp>
    +<actuators/Motor.cpp>
    +<sensors/MagneticEncoder.cpp>
    +<test/arm/calibrate_arm.cpp>

[env:test_base_gear]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<actuators/BaseGear.cpp>
    +<actuators/Motor.cpp>
    +<sensors/MagneticEncoder.cpp>
    +<test/base_gear>

[env:test_cascade]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<test/cascade>
    +<actuators/Motor.cpp>

[env:test_mag]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<sensors/MagneticEncoder.cpp>
    +<test/mag>

[env:test_sonar]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<sensors/Sonar.cpp>
    +<test/sonar>

[env:test_switch]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<test/switch>

[env:test_tof]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<actuators/Arm.cpp>
    +<actuators/Servo.cpp>
    +<sensors/ToF.cpp>
    +<test/tof>
lib_deps = 
    sparkfun/SparkFun VL53L5CX Arduino Library@^1.0.3

[env:test_timer]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<test/timer>

[env:test_tasks]
platform = espressif32
board = pico32
framework = arduino
monitor_speed = 115200
build_src_filter = 
    +<test/tasks>