#ifndef EVENTS_H
#define EVENTS_H

typedef enum {
    EVENT_NONE,
    EVENT_PET_DETECTED_LEFT,
    EVENT_PET_DETECTED_RIGHT,
    EVENT_PILLAR_DETECTED,
    EVENT_PET_NEAR,
    EVENT_PET_MISSED,
    EVENT_ARM_READY,
    EVENT_PET_FAILED,
    EVENT_PET_GRASPED,
    EVENT_PET_STORED,
    EVENT_EDGE_DETECTED,
    EVENT_PETS_RETURNED,
    EVENT_RAMP,
    EVENT_FIRST_PET_GRASPED,
} state_event_e;

#endif