#ifndef EVENTS_H
#define EVENTS_H

typedef enum {
    STATE_EVENT_NONE,
    STATE_EVENT_BUTTON_PRESSED,
    STATE_EVENT_TAPE_DETECTED,
    STATE_EVENT_PET_DETECTED,
    STATE_EVENT_PILLAR_DETECTED,
    STATE_EVENT_NEAR_PET,
    STATE_EVENT_PET_GRASPED,
    STATE_EVENT_PET_STORED,
    STATE_EVENT_RAMP_DETECTED,
    STATE_EVENT_DEBRIS_DETECTED,
    STATE_EVENT_FLAT_GROUND_DETECTED,
    STATE_EVENT_EDGE_DETECTED,
    STATE_EVENT_CASCADE_EXTENDED,
    STATE_EVENT_ZIP_LINE_DETECTED, // probably a timer
} state_event_e;

#endif