#ifndef EVENTS_H
#define EVENTS_H

typedef enum {
    EVENT_NONE,
    EVENT_BUTTON_PRESSED,
    EVENT_TAPE_DETECTED,
    EVENT_PET_DETECTED,
    EVENT_PILLAR_DETECTED,
    EVENT_ARM_RAISED,
    EVENT_NEAR_PET,
    EVENT_PET_GRASPED,
    EVENT_PET_STORED,
    EVENT_RAMP_DETECTED,
    EVENT_DEBRIS_DETECTED,
    EVENT_FLAT_GROUND_DETECTED,
    EVENT_EDGE_DETECTED,
    EVENT_CASCADE_EXTENDED,
    EVENT_ZIP_LINE_DETECTED, // probably a timer
} state_event_e;

#endif